background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 1.2
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

general {
    hide_cursor = true
    grace = 2
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2

    dots_size = 0.22
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgb(cba6f7)
    inner_color = rgba(30, 30, 46, 0.85)
    font_color = rgb(cdd6f4)

    fade_on_empty = false
    placeholder_text = <i>Password...</i>

    rounding = 14

    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(cdd6f4)

    font_size = 72
    font_family = SF Pro Display Bold

    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgb(bac2de)

    font_size = 18
    font_family = SF Pro Display

    position = 0, 20
    halign = center
    valign = center
}
