[pyprland]
plugins = ["scratchpads"]

[scratchpads.spotify]
#animation = "fromTop"
command = "spotify"
class = "Spotify"
size = "75% 85%"
margin = 60
lazy = true
unfocus = "hide"

[scratchpads.sp]
#animation = "fromTop"
command = "super-productivity"
class = "superproductivity"
size = "65% 55%"
margin = 60
lazy = true
unfocus = "hide"
