#!/usr/bin/env bash
# ScreenShoTer - Screenshot tool using grim+slurp (ported from bspwm)

timestamp=$(date +%Y-%m-%d-%H%M%S)
dir="$(xdg-user-dir PICTURES)/ScreenShots"
filename="$dir/Shot-${timestamp}.png"

[ -d "$dir" ] || mkdir -p "$dir"

s_full=""
s_select=""
s_in3="󰔝"
s_all="󰍹"

rofi_cmd() {
    rofi -dmenu \
        -p Screenshot \
        -mesg "Directory :: $dir" \
        -markup-rows \
        -theme "$HOME/.config/hypr/rofi/screenshot.rasi"
}

run_rofi() {
    printf "%s\n%s\n%s\n%s\n" "$s_full" "$s_select" "$s_in3" "$s_all" | rofi_cmd
}

show_notification() {
    if [ -e "$filename" ]; then
        action=$(dunstify \
            -r 699 \
            -i "$filename" \
            -A "open,Open" \
            "Screenshot" \
            "Screenshot saved and copied to clipboard")

        [ "$action" = "open" ] && xdg-open "$filename"

    else
        dunstify \
            -r 699 \
            -i user-trash \
            "Screenshot" \
            "Screenshot canceled"
    fi
}

copy_screenshot() {
    wl-copy < "$filename"
}

take_screenshot() {
    sleep 0.2
    mode="$1"
    all_monitors="$2"

    case "$mode" in
        "full")
            if [ "$all_monitors" != "true" ]; then
                grim -s 1 "$filename"
            else
                grim -s 1 -o "$(hyprctl monitors -j | jq -r '.[] | select(.focused==true).name')" "$filename"
            fi
            ;;
        "select")
            grim -s 1 -g "$(slurp)" "$filename"
            ;;
    esac

    if [ "$?" -eq 0 ]; then
        paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga > /dev/null 2>&1
        copy_screenshot
        show_notification
    fi
}

countdown() {
    for sec in $(seq "$1" -1 1); do
        dunstify -r 345 -t 1100 -i ~/.config/hypr/assets/screenshot.png "Taking shot in : $sec"
        sleep 1
    done
}

run_cmd() {
    case $1 in
        --now)
            take_screenshot "full" false ;;
        --sel)
            take_screenshot "select" false ;;
        --in3)
            countdown 3 && take_screenshot "full" false ;;
        --all)
            take_screenshot "full" true ;;
    esac
}

select_option="$(run_rofi)"
case ${select_option} in
    "$s_full")
        run_cmd --now ;;
    "$s_select")
        run_cmd --sel ;;
    "$s_in3")
        run_cmd --in3 ;;
    "$s_all")
        run_cmd --all ;;
esac
